config/routes.rb
Rails4::Application.routes.draw do
  
  get '/author/search', to: 'authors#search_author', as: 'search_author'
  get '/book/search', to: 'books#search_book', as: 'search_book'
  
  resources :books

  resources :authors

  

  
  root to: "authors#index"
  
end

app/models/author.rb
class Author < ActiveRecord::Base
  has_many :books  
  scope :name_like, ->(author_name){ where("name like '%#{author_name}%'")}
    
end

app/models/book.rb
class Book < ActiveRecord::Base
  
  store_accessor :details, [:title, :description]
  
  belongs_to :author
  default_scope order("id asc")
  scope :of, ->(author_id){ where("author_id = ?", author_id) }
  scope :title_like, ->(title){ where("details -> 'title' like '%#{title}%'") }
  scope :description_like, ->(description){ where("details -> 'description' like '%#{description}%'") }
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render action: 'show', status: :created, location: @author }
      else
        format.html { render action: 'new' }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url }
      format.json { head :no_content }
    end
  end
  
  def search_author
    @authors = Author.name_like params[:author_name]
    render action: :index
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:name, :age)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    if params[:author_id]
      @books = Book.includes(:author).of(params[:author_id])
    else
      @books = Book.includes(:author).all
    end
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render action: 'show', status: :created, location: @book }
      else
        format.html { render action: 'new' }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url }
      format.json { head :no_content }
    end
  end
  
  def search_book
    @books = Book.title_like params[:book_name]
    render action: :index
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:price, :title, :description, :author_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
  
  def authors_select
    Author.all.map{|author| [author.name, author.id] }
  end
  
end

app/views/authors/_form.html.erb
<%= form_for(@author) do |f| %>
  <% if @author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% @author.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.text_field :age %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1>Editing author</h1>

<%= render 'form' %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.haml
%h1
  Listing authors

%table
  %thead
    %tr
      %th
        Name
      %th
        Age
      %th
      %th
      %th
      %th
  %tbody
    - @authors.each do |author|
      %tr
        %td
          = author.name
        %td
          = author.age
        %td
          = link_to "View Books", books_path(author_id: author.id)
        %td
          = link_to 'Show', author
        %td
          = link_to 'Edit', edit_author_path(author)
        %td
          = link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Author', new_author_path

app/views/authors/new.html.erb
<h1>New author</h1>

<%= render 'form' %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.haml
%p
  %strong
    Name:
  = @author.name
%p
  %strong
    Age:
  = @author.age
= link_to "View Books", books_path(author_id: @author.id )
|
= link_to 'Edit', edit_author_path(@author)
|
= link_to 'Back', authors_path

app/views/books/_form.html.haml
= form_for(@book) do |f|
  - if @book.errors.any?
    #error_explanation
      %h2
        = pluralize(@book.errors.count, "error")
        prohibited this book from being saved:

      %ul
        - @book.errors.full_messages.each do |msg|
          %li
            = msg
  .field
    = f.label :Author
    %br/
    = f.select :author_id, authors_select
  .field
    = f.label :title
    %br/
    = f.text_field :title
  .field
    = f.label :description
    %br/
    = f.text_field :description
  .field
    = f.label :price
    %br/
    = f.text_field :price
  .actions
    = f.submit

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.haml
%h1 
  Listing books
%table
  %thead
    %tr
      %th Title
      %th Description
      %th Price
      %th
      %th
      %th
  %tbody
    - @books.each do |book|
      %tr
        %td= book.title
        %td= book.description
        %td= book.price
        %td= link_to 'Show', book
        %td= link_to 'Edit', edit_book_path(book)
        %td= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Book', new_book_path

app/views/books/new.html.erb
<h1>New book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Description</strong>
  <%= @book.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @book.price %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/layouts/_top_nav.html.haml
#top_nav
  = link_to "Authors", authors_path
  = link_to "Books", books_path
  %br
  = form_tag search_author_path, method: :get do
    = label_tag :search, "Search Author", style: "float: left;"
    = text_field_tag :author_name, "", style: "float: left;"
    = submit_tag "Go"
  = form_tag search_book_path, method: :get do
    = label_tag :search, "Search Book", style: "float: left;"
    = text_field_tag :book_name, "", style: "float: left;"
    = submit_tag "Go"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rails4</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="container">
	<%= render partial: "layouts/top_nav" %>
	<%= yield %>
</div>

</body>
</html>